//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleCMS.Views.Dashboard.Posts {
    
    
    public partial class CreatePost {
        
        /// <summary>
        /// Edit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::SimpleCMS.Views.PostEdit Edit;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new SimpleCMS.Views.Dashboard.Layout Master {
            get {
                return ((SimpleCMS.Views.Dashboard.Layout)(base.Master));
            }
        }
    }
}
